---
- name: Install NTP and OpenStack Components
  hosts: all
  become: yes
  tasks:
    - name: Install NTP
      apt:
        name: chrony
        state: present
      when: ansible_os_family == "Debian"

    - name: Install OpenStack packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3-openstackclient
        - nova-compute
        - neutron-server
        - glance
        - keystone
      when: ansible_os_family == "Debian"

    - name: Install SQL Database
      apt:
        name: mysql-server
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Message Queue
      apt:
        name: rabbitmq-server
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Memcached
      apt:
        name: memcached
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Etcd
      apt:
        name: etcd
        state: present
      when: ansible_os_family == "Debian"

  handlers:
    - name: restart chronyd
      service:
        name: chronyd
        state: restarted
